### ISSUE TITLE
Interaktive Aufgaben

### ISSUE THREAD

**Issue by jprberlin** [openHPI/codeocean#1]
Es sollte möglich sein Aufgaben zu haben, bei denen durch den Lerner ein oder mehrere Eingaben erfolgen kann. 
Mögliche Implementierung über WebSockets.

**Comment by hklement** [comment]
Since Code Ocean employs container pooling, providing input to containers is used internally. When implementing interactive I/O, the current behavior should be maintained.

When obtained from the container pool, every container has to be provided with a context-specific command to execute. This way, the container pool must only maintain a set of homogeneous containers per execution environment although their usage contexts vary. The specific command to execute is currently provided using a [`StringIO`](http://ruby-doc.org/stdlib-1.9.3/libdoc/stringio/rdoc/StringIO.html) instance.
