### ISSUE TITLE
Hybrid Cloud / Outbreak

### ISSUE THREAD

**Issue by janrenz** [openHPI/codeocean#2]
Wie kann man CodeOcean dazu bringen die Docker Container in einer Public Cloud zu starten. 

Fragen: Verträgt sich das mit dem momentanen Pooling Ansatz?
Was muss man sonst noch beachten (bspw. dürfen keine Volume Shares verwendet werden sondern alle Kommunikation und Anlegen von Dateien muss über HTTP(S) / Docker API erfolgen.

**Comment by hklement** [comment]
Code Ocean currently uses a single Docker server, which has to be configured using the `docker.yml`. However, [the utilized gem wrapping Docker's API](https://github.com/swipely/docker-api) should support [connecting to multiple Docker servers](https://github.com/swipely/docker-api#connecting-to-multiple-servers).

Besides calls to Docker's API, executing a code submission involves the following file system operations:
- Creating a submission-specific directory and a virtual volume. This already happens when a container is added to the container pool.
- Creating submission-specific files. This happens shortly before code execution.
- Cleaning up the directory. This happens shortly after execution.

As multi-server environments were not relevant yet, file system operations are not implemented in a generic fashion. Currently, these operations are performed locally in a directory expected to be accessible for the Docker server.

An alternative strategy could be creating and deleting file system objects using SFTP.

**Comment by MrSerth** [comment]
With the introduction of [Poseidon](https://github.com/openHPI/poseidon), we've come closer to allow a hybrid deployment of CodeOcean. With Poseidon, CodeOcean and the code execution are decoupled, and are run on different machines. The two services communicate through a REST API, which also includes support for remote file operations.

Further, we've integrated AWS Lambda as a serverless solution for CodeOcean and successfully showed the feasibility (and limitations) of this technology for the given use case. More details are available in the following publication:

> S. Serth, M. Paß, C. Meinel: On the Feasibility of Serverless Functions in the Context of Auto-Graders. In: 2023 IEEE German Education Conference (GeCon). 6 pages. IEEE, Berlin, Germany (2023).

Therefore, I am closing this issue has being resolved.
