### ISSUE TITLE
Wrong filename passed to ws exec when asking to run a file

### ISSUE THREAD

**Issue by jgraichen** [openHPI/codeocean#220]
When selecting a file in the editor and clicking `Run` I'd expected to have this file run. Instead the main file is run.

This is seems to be related to the `this.active_file` in `editor/editor.js.erb` which is *not* set when [a file is selected](https://github.com/openHPI/codeocean/blob/0395d5b03826e382f2c39eadb79710dfb995c693/app/assets/javascripts/editor/editor.js.erb#L270). It seems to never change from the default main file set on [initialization](https://github.com/openHPI/codeocean/blob/0395d5b03826e382f2c39eadb79710dfb995c693/app/assets/javascripts/editor/editor.js.erb#L208).

All run actions will therefore always only run the main file rendering user-defined tests useless.

**Comment by MrSerth** [comment]
We've changed the implementation of running files some time ago. By now, a project can contain multiple different file roles, that are handled specifically. In more detail:
- A `main file` is run as a default
- An `executable file` can be triggered by learners through the `Run` button
- A `test file` (if visible) changes the button to `Test` and solely executes that test (running it with the `test` command)
- A `linter file` (if visible) behaves similar to a `test file` (action is `Test`)
- A `user-defined test` features a `Test` action rather than run, too
- A `user-defined file` can be `Run`
- A `reference file` and a `regular file` currently have no run action associated (`No action` is displayed)
- A `renderable file` (a property of a file type, not a file role, e.g., HTML files) have an action called `Render` opening the rendered version of the file in a new tab.

That having said, I am confident that the issue has been resolved already and can be closed.
